module softmax #(
    // parameters
    parameter int NUM_INPUTS = 8,
    parameter int INPUT_WIDTH = 11,
    parameter int OUTPUT_WIDTH = 8
)(
    input logic clk,
    input logic rst_n,
    input logic [NUM_INPUTS*INPUT_WIDTH-1:0] inputs,
    input logic valid_in,
    output logic valid_out,
    output logic [NUM_INPUTS*OUTPUT_WIDTH-1:0] weights_flat
);

// unpack inputs
    logic signed [INPUT_WIDTH-1:0] scores [NUM_INPUTS-1:0];
    
    // internal pipeline signals
    logic signed [INPUT_WIDTH-1:0] max_val;
    logic signed [INPUT_WIDTH:0] shifted [NUM_INPUTS-1:0];
    logic [OUTPUT_WIDTH-1:0]       exp_val [NUM_INPUTS-1:0];
    logic [10:0] exp_sum;  // 11 bits: holds up to 8 × 255 = 2040
    logic [OUTPUT_WIDTH-1:0]       weights [NUM_INPUTS-1:0];

    localparam int LUT_SHIFT = 4;  // log2(16) — RTL divides by right-shifting

    // unpack flat input into array
    genvar i;
    generate
        for (i = 0; i < NUM_INPUTS; i++) begin
            assign scores[i] = inputs[INPUT_WIDTH*(i+1)-1 -: INPUT_WIDTH];
        end
    endgenerate

    // Stage 1 — find maximum score
always_comb begin
    max_val = scores[0];
    for (int j = 1; j < NUM_INPUTS; j++) begin
        if ($signed(scores[j]) > $signed(max_val))
            max_val = scores[j];
    end
end

always_comb begin
    for (int j = 0; j < NUM_INPUTS; j++) begin
        shifted[j] = (scores[j]) - (max_val);
    end
end

// Stage 3 — exp() LUT lookup
    // get_exp_val(n) = round(255 * exp(-n / 16)); body generated by
    // tb/gen_exp_lut.py — rerun that script if LUT_SHIFT changes.
    // default: covers both "genuinely decayed to zero" indices and any
    // index that falls outside this table entirely (out-of-range clamp).
    function automatic logic [OUTPUT_WIDTH-1:0] get_exp_val(input logic signed [INPUT_WIDTH:0] shift_val);
        logic signed [INPUT_WIDTH:0] idx;
        idx = (-shift_val) >>> LUT_SHIFT;
        case (idx)
            0: get_exp_val = 8'd255;
            1: get_exp_val = 8'd240;
            2: get_exp_val = 8'd225;
            3: get_exp_val = 8'd211;
            4: get_exp_val = 8'd199;
            5: get_exp_val = 8'd187;
            6: get_exp_val = 8'd175;
            7: get_exp_val = 8'd165;
            8: get_exp_val = 8'd155;
            9: get_exp_val = 8'd145;
            10: get_exp_val = 8'd136;
            11: get_exp_val = 8'd128;
            12: get_exp_val = 8'd120;
            13: get_exp_val = 8'd113;
            14: get_exp_val = 8'd106;
            15: get_exp_val = 8'd100;
            16: get_exp_val = 8'd94;
            17: get_exp_val = 8'd88;
            18: get_exp_val = 8'd83;
            19: get_exp_val = 8'd78;
            20: get_exp_val = 8'd73;
            21: get_exp_val = 8'd69;
            22: get_exp_val = 8'd64;
            23: get_exp_val = 8'd61;
            24: get_exp_val = 8'd57;
            25: get_exp_val = 8'd53;
            26: get_exp_val = 8'd50;
            27: get_exp_val = 8'd47;
            28: get_exp_val = 8'd44;
            29: get_exp_val = 8'd42;
            30: get_exp_val = 8'd39;
            31: get_exp_val = 8'd37;
            32: get_exp_val = 8'd35;
            33: get_exp_val = 8'd32;
            34: get_exp_val = 8'd30;
            35: get_exp_val = 8'd29;
            36: get_exp_val = 8'd27;
            37: get_exp_val = 8'd25;
            38: get_exp_val = 8'd24;
            39: get_exp_val = 8'd22;
            40: get_exp_val = 8'd21;
            41: get_exp_val = 8'd20;
            42: get_exp_val = 8'd18;
            43: get_exp_val = 8'd17;
            44: get_exp_val = 8'd16;
            45: get_exp_val = 8'd15;
            46: get_exp_val = 8'd14;
            47: get_exp_val = 8'd14;
            48: get_exp_val = 8'd13;
            49: get_exp_val = 8'd12;
            50: get_exp_val = 8'd11;
            51: get_exp_val = 8'd11;
            52: get_exp_val = 8'd10;
            53: get_exp_val = 8'd9;
            54: get_exp_val = 8'd9;
            55: get_exp_val = 8'd8;
            56: get_exp_val = 8'd8;
            57: get_exp_val = 8'd7;
            58: get_exp_val = 8'd7;
            59: get_exp_val = 8'd6;
            60: get_exp_val = 8'd6;
            61: get_exp_val = 8'd6;
            62: get_exp_val = 8'd5;
            63: get_exp_val = 8'd5;
            64: get_exp_val = 8'd5;
            65: get_exp_val = 8'd4;
            66: get_exp_val = 8'd4;
            67: get_exp_val = 8'd4;
            68: get_exp_val = 8'd4;
            69: get_exp_val = 8'd3;
            70: get_exp_val = 8'd3;
            71: get_exp_val = 8'd3;
            72: get_exp_val = 8'd3;
            73: get_exp_val = 8'd3;
            74: get_exp_val = 8'd2;
            75: get_exp_val = 8'd2;
            76: get_exp_val = 8'd2;
            77: get_exp_val = 8'd2;
            78: get_exp_val = 8'd2;
            79: get_exp_val = 8'd2;
            80: get_exp_val = 8'd2;
            81: get_exp_val = 8'd2;
            82: get_exp_val = 8'd2;
            83: get_exp_val = 8'd1;
            84: get_exp_val = 8'd1;
            85: get_exp_val = 8'd1;
            86: get_exp_val = 8'd1;
            87: get_exp_val = 8'd1;
            88: get_exp_val = 8'd1;
            89: get_exp_val = 8'd1;
            90: get_exp_val = 8'd1;
            91: get_exp_val = 8'd1;
            92: get_exp_val = 8'd1;
            93: get_exp_val = 8'd1;
            94: get_exp_val = 8'd1;
            95: get_exp_val = 8'd1;
            96: get_exp_val = 8'd1;
            97: get_exp_val = 8'd1;
            98: get_exp_val = 8'd1;
            99: get_exp_val = 8'd1;
            default: get_exp_val = 8'd0;
        endcase
    endfunction

always_comb begin
    for (int j = 0; j < NUM_INPUTS; j++) begin
        exp_val[j] = get_exp_val(shifted[j]);
    end
end

always_comb begin
    exp_sum = 0;
    for (int j = 0; j < NUM_INPUTS; j++) begin
        exp_sum += exp_val[j];
    end
end

function automatic logic [OUTPUT_WIDTH-1:0] get_weight(
    input logic [OUTPUT_WIDTH-1:0] exp_val_i,
    input logic [10:0] sum
);
    logic [15:0] raw;  // exp_val_i * 256 maxes at 255*256=65280, fits in 16 bits
    raw = (exp_val_i * 256) / sum;
    if(raw > 255) begin
        get_weight = 8'd255;
    end else begin
        get_weight = raw[7:0];
    end
endfunction

always_comb begin
    for (int j = 0; j < NUM_INPUTS; j++) begin
        weights[j] = get_weight(exp_val[j], exp_sum);
    end
end

always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        valid_out <= 0;
        weights_flat <= '0;
    end else begin
        valid_out <= valid_in;
        if (valid_in) begin
            for (int j = 0; j < NUM_INPUTS; j++) begin
                weights_flat[OUTPUT_WIDTH*(j+1)-1 -: OUTPUT_WIDTH] <= weights[j];
            end
        end
    end
end

endmodule